apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test-app-ingress
  labels:
    app: test-app
spec:
  entryPoints: [web]
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - kind: Service
          name: test-app-service
          port: 5000
          scheme: http